server:
  port: ${SERVER_PORT:8080}
  servlet:
    context-path: /debezium
  max-http-header-size: 128KB

spring:
  application:
    name: debezium
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:uat}
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 10MB
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    com.boxuegu.debezium: debug

rocket:
  name-server-addr: ${ROCKET_NAME_SERVER_ADDR:172.16.1.36:9876}
  access-key: ${ROCKET_ACCESS_KEY:AAA}
  secret-key: ${ROCKET_SECRET_KEY:BBB}
  send-msg-timeout-millis: 10000

debezium:
  database:
    server-name: ${DB_SERVER_NAME:bxg_db_server}
    server-id: ${DB_SERVER_ID:1}
    ip: ${DB_SERVER_IP:172.19.147.203}
    port: ${DB_SERVER_PORT:3306}
    user: ${DB_USER:canal}
    password: ${DB_PWD:canal}
  cdc:
    db-include-list: ${DB_INCLUDE_LIST:db_test}
    table-include-list: ${TABLE-INCLUDE-LIST:db_test.t_employee}
    offset-file: ${OFFSET_FILE:/tmp/offsets.dat}
    history-file: ${HISTORY_FILE:/tmp/dbhistory.dat}